server:
  port: 8088

#emp的配置数据
#emp:
#  lastName: zhangshan
#  age: 22
#  salary: 20000
#  boss: true
#  birthday: 1995/12/25
#  map:
#    key1: value1
#    key2: value2
#  list:
#    - one
#    - two
#    - three
#  forte:
#    name: java
#    time: 8


