
spring:
  datasource:
    username: root
    password: 170130
    #使用 MySQL连接驱动是8.0以上，需要在Url后面加上时区, GMT%2B8代表中国时区，不然报时区错误
    url: jdbc:mysql://127.0.0.1:3306/jdbc?serverTimezone=GMT%2B8
    # 注意： 新版本驱动包，要使用以下类作为驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
